[build]
  publish = "web"
  command = ""

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.19.0"
  GO_IMPORT_PATH = "github.com/daquan-work/corusync"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
